intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{cppcodec}: {hxx ixx txx}{**} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{cppcodec}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# Install into the cppcodec/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/cppcodec/
  install.subdirs = true
}
